const SPARKPOST_ENDPOINT = process.env.SPARKPOST_ENDPOINT;
const SPARKPOST_API_KEY = process.env.SPARKPOST_API_KEY || '056122085a0464e9529d2d28ecb9c85f387fdb80';
const DEFAULT_SENDER_EMAIL_ADDRESS = process.env.DEFAULT_SENDER_EMAIL_ADDRESS;
const WEB_APP_URL = process.env.WEB_APP_URL;
const EMAIL_TEMPLATE_TABLE = process.env.EMAIL_TEMPLATE_TABLE || 'easyemail';
module.exports = {
  SPARKPOST_ENDPOINT,
  SPARKPOST_API_KEY,
  DEFAULT_SENDER_EMAIL_ADDRESS,
  WEB_APP_URL,
  EMAIL_TEMPLATE_TABLE
};
